CREATE TABLE `addresses`(
add_ID INT(12) PRIMARY KEY AUTO_INCREMENT,
zipcode INT(5) NOT NULL,
state_name VARCHAR(50) NOT NULL,
city_name VARCHAR(50) NOT NULL,
adress VARCHAR(255) NOT NULL,
address2 VARCHAR(255) NOT NULL,
add_created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
add_modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

CREATE TABLE `users`
(
userId INT(12) PRIMARY KEY AUTO_INCREMENT,
login VARCHAR(255) NOT NULL,
u_password VARCHAR(255) NOT NULL,
user_IsActive BOOLEAN NOT NULL,
role VARCHAR(255) DEFAULT 'patient' NOT NULL,
created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) 


CREATE TABLE `doc_spec` (
spec_ID INT(12) PRIMARY KEY AUTO_INCREMENT,
spec_name VARCHAR(255) NOT NULL
) 

CREATE TABLE `insurance` (
ins_ID INT(12) PRIMARY KEY AUTO_INCREMENT,
ins_name VARCHAR(120) NOT NULL,
ins_phone INT(10) NOT NULL,
ins_web_link VARCHAR(255) NOT NULL
)


CREATE TABLE `doctors` (
doctorID INT(12) PRIMARY KEY AUTO_INCREMENT,
doc_firstname VARCHAR(45) NOT NULL,
doc_lastname VARCHAR(50) NOT NULL,
doc_NPI INT(10) NOT NULL,
doc_isActive BOOLEAN NOT NULL DEFAULT true,
doc_reg_date TIMESTAMP NOT NULL,
doc_email VARCHAR(100) NOT NULL,
doc_phone INT(10) NOT NULL,
doc_img_link VARCHAR(255) NOT NULL,
doc_address_ID INT(12) NOT NULL,
CONSTRAINT `FK_address_ID` FOREIGN KEY(doc_address_ID) REFERENCES addresses(add_ID)
ON DELETE CASCADE
ON UPDATE CASCADE,
doc_gender ENUM('M','F'),
doc_education VARCHAR(255) NOT NULL,

doc_specialization_ID INT(12) NOT NULL,
CONSTRAINT `FK_spec_ID`
FOREIGN KEY(doc_specialization_ID) REFERENCES doc_spec(spec_ID),

doc_insurance_accep_ID INT(12) NOT NULL,
CONSTRAINT `FK_ins_ID`
 FOREIGN KEY(doc_insurance_accep_ID) REFERENCES insurance(ins_ID),
 
doc_user_table_ID INT(12) NOT NULL,
CONSTRAINT `FK_user_table_id`
FOREIGN KEY(doc_user_table_ID) REFERENCES users(UserId)
ON DELETE CASCADE
ON UPDATE CASCADE,
doc_created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
doc_modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) 

CREATE TABLE `patients` (
patient_ID INT(12) PRIMARY KEY AUTO_INCREMENT,
p_firstname VARCHAR(45) NOT NULL,
p_lastname VARCHAR(100) NOT NULL,
p_Ins_CardNumber VARCHAR(50),
p_Email VARCHAR(100) NOT NULL,
p_isActive BOOLEAN NOT NULL DEFAULT true,
p_DOB DATE,
p_gender ENUM('M','F') NOT NULL,
p_address_ID INT(12) NOT NULL,
CONSTRAINT `FK_add_ID2`
FOREIGN KEY (p_address_ID) REFERENCES addresses(add_ID)
ON DELETE CASCADE
ON UPDATE CASCADE,
p_phone INT(10) NOT NULL,
p_emergency_contact_num INT(10),
p_insuranceName INT(12) NOT NULL,
CONSTRAINT `FK_ins_ID2`
FOREIGN KEY (p_insuranceName) REFERENCES insurance(ins_ID),
p_file_ID INT(12) NOT NULL,
CONSTRAINT `FK_file_ID`
FOREIGN KEY (p_file_ID) REFERENCES files(file_id),

p_user_table_ID INT(12) NOT NULL,
CONSTRAINT `FK_p_user_table_id`
FOREIGN KEY(p_user_table_ID) REFERENCES users(UserId)
ON DELETE CASCADE
ON UPDATE CASCADE,
pat_created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
pat_modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)


CREATE TABLE medhistory(
record_ID INT(12) PRIMARY KEY AUTO_INCREMENT,
patient_ID INT(12) NOT NULL,
CONSTRAINT `FK_patID`
FOREIGN KEY (patient_ID) REFERENCES patients(patient_ID),
doctor_ID INT(12) NOT NULL,
CONSTRAINT `FK_docID`
FOREIGN KEY (doctor_ID) REFERENCES doctors(doctorID),
description VARCHAR(800) NOT NULL,
commentary VARCHAR(800),
file_image_ID INT(12) NOT NULL, 
CONSTRAINT `FK_fileID2`
FOREIGN KEY (file_image_ID) REFERENCES files(file_id),
created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)